name: build-kernel
on:
  push:
jobs:
  build-kernel:
    runs-on: self-hosted
    steps:
      - run: |
          tar -xf /mnt/wrk_files/kernel/5.15.16/linux-5.15.16.tar.xz
          cd linux-5.15.16
          cp /mnt/wrk_files/kernel/5.15.16/config/active .config
          make -j8
      - run: ls -haltr ./linux-5.15.16/arch/x86/boot/compressed/vmlinux
      - run: cp ./linux-5.15.16/arch/x86/boot/compressed/vmlinux /mnt/wrk_files/kernel/5.15.16/archive/vmlinux_$(date +"%m-%d-%Y_%H.%M.%S")
      - run: rm -rf /tmp/wrk/kernel-configs/*
      
      
      
 
